---
- name: make sure all required programs are installed
  # ...
- name: create bare git repo
  command: git init --bare ~/.dotfiles
- name: configure dotfiles repo
  # ...
- name: create sparecheckout file
  # ...
- name: pull in files
  # ...
